"""RSS feed generation: valid XML, published-only, newest first."""
from __future__ import annotations

from xml.etree import ElementTree

from app.services import rss


def _project(**overrides):
    from app.models.project import Project, Tone

    defaults = dict(
        id=1,
        user_id=1,
        name="Pulse & Friends",
        slug="herald",
        description="Marketing automation, <auto-generated>.",
        live_url="https://herald.example.com",
        tone=Tone.TECHNICAL,
    )
    defaults.update(overrides)
    return Project(**defaults)


def _content(**overrides):
    from app.models.content import Content, ContentStatus, ContentType

    defaults = dict(
        id=1,
        project_id=1,
        content_type=ContentType.ANNOUNCEMENT,
        status=ContentStatus.PUBLISHED,
        title="Pulse 1.0",
        slug="herald-1-0",
        excerpt="The first release.",
    )
    defaults.update(overrides)
    return Content(**defaults)


def test_feed_is_well_formed_xml_with_expected_channel_fields():
    project = _project()
    xml = rss.build_feed(project, [], self_url="https://herald.example.com/api/v1/projects/1/feed.xml")

    root = ElementTree.fromstring(xml)
    assert root.tag == "rss"
    channel = root.find("channel")
    assert channel.find("title").text == "Pulse & Friends"
    assert channel.find("link").text == "https://herald.example.com"


def test_feed_escapes_special_characters_in_title_and_description():
    project = _project()
    xml = rss.build_feed(project, [], self_url="https://herald.example.com/feed.xml")
    # ElementTree.fromstring would itself raise on unescaped "&" or "<" — the
    # real assertion here is that parsing succeeds and the value round-trips.
    root = ElementTree.fromstring(xml)
    assert root.find("channel/description").text == "Marketing automation, <auto-generated>."


def test_feed_includes_items_with_canonical_link_and_guid():
    project = _project()
    content = _content(canonical_url="https://devto.example.com/herald-1-0")
    xml = rss.build_feed(project, [content], self_url="https://herald.example.com/feed.xml")

    root = ElementTree.fromstring(xml)
    items = root.findall("channel/item")
    assert len(items) == 1
    assert items[0].find("title").text == "Pulse 1.0"
    assert items[0].find("link").text == "https://devto.example.com/herald-1-0"
    assert items[0].find("guid").text == "herald-content-1"
    assert items[0].find("guid").attrib["isPermaLink"] == "false"
    assert items[0].find("description").text == "The first release."


def test_feed_falls_back_to_project_site_slug_when_no_canonical_url():
    project = _project(live_url="https://herald.example.com")
    content = _content(canonical_url=None)
    xml = rss.build_feed(project, [content], self_url="https://herald.example.com/feed.xml")

    root = ElementTree.fromstring(xml)
    assert root.find("channel/item/link").text == "https://herald.example.com/herald-1-0"
