"""initial schema

Revision ID: a1b2c3d4e5f6
Revises: 
Create Date: 2026-07-25 21:54:01.247739
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a1b2c3d4e5f6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('platform_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('MEDIUM', 'DEVTO', 'HASHNODE', 'LINKEDIN', 'TWITTER', 'WORDPRESS', name='platform', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('CONNECTED', 'INVALID', 'DISCONNECTED', name='connectionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform', name='uq_connection_user_platform')
    )
    with op.batch_alter_table('platform_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_connections_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=True),
    sa.Column('live_url', sa.String(length=500), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('tone', sa.Enum('TECHNICAL', 'CASUAL', 'MARKETING', name='tone', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('autopilot_mode', sa.Enum('OFF', 'DRAFT', 'AUTO', name='autopilotmode', native_enum=False, length=20), nullable=False),
    sa.Column('autopilot_platforms', sa.JSON(), nullable=False),
    sa.Column('last_seen_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('last_seen_release_tag', sa.String(length=120), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)

    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('TUTORIAL', 'ANNOUNCEMENT', 'FEATURE_SPOTLIGHT', 'COMPARISON', 'HOW_TO', name='contenttype', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED', 'FAILED', name='contentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=320), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('meta_description', sa.String(length=320), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('canonical_url', sa.String(length=500), nullable=True),
    sa.Column('generated_by_provider', sa.String(length=40), nullable=True),
    sa.Column('generated_by_model', sa.String(length=120), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.JSON(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_status'), ['status'], unique=False)

    op.create_table('content_ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('TUTORIAL', 'ANNOUNCEMENT', 'FEATURE_SPOTLIGHT', 'COMPARISON', 'HOW_TO', name='contenttype', native_enum=False, length=30), nullable=False),
    sa.Column('headline', sa.String(length=300), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('source', sa.JSON(), nullable=False),
    sa.Column('used_content_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_ideas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_ideas_project_id'), ['project_id'], unique=False)

    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('MEDIUM', 'DEVTO', 'HASHNODE', 'LINKEDIN', 'TWITTER', 'WORDPRESS', name='platform', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULED', 'PUBLISHING', 'PUBLISHED', 'FAILED', 'CANCELLED', name='publicationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('external_url', sa.String(length=700), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'platform', name='uq_publication_content_platform')
    )
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publications_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_status'), ['status'], unique=False)

    op.create_table('content_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('reads', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('reactions', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_metrics_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_metrics_publication_id'), ['publication_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_metrics_publication_id'))
        batch_op.drop_index(batch_op.f('ix_content_metrics_captured_at'))

    op.drop_table('content_metrics')
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publications_status'))
        batch_op.drop_index(batch_op.f('ix_publications_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_publications_platform'))
        batch_op.drop_index(batch_op.f('ix_publications_content_id'))

    op.drop_table('publications')
    with op.batch_alter_table('content_ideas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_ideas_project_id'))

    op.drop_table('content_ideas')
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_status'))
        batch_op.drop_index(batch_op.f('ix_content_slug'))
        batch_op.drop_index(batch_op.f('ix_content_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_content_project_id'))

    op.drop_table('content')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))
        batch_op.drop_index(batch_op.f('ix_projects_slug'))

    op.drop_table('projects')
    with op.batch_alter_table('platform_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_connections_user_id'))

    op.drop_table('platform_connections')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
